### ISSUE TITLE
Fix the API call in the backend

### ISSUE THREAD

**Issue by shiryz** [lotus-1/WebAppNews-AME#19]
https://github.com/lotus-1/WebAppNews-AME/blob/master/src/handler.js#L46

If you look at the [docs](https://newsapi.org/) you'll find that you're missing a category in the url you're using 
So your call should look something like this ...newsapi.org/v2/top-headlines?__country=us__&__category=business__&apiKey=API_KEY

You need to specify the country you're looking for news in and then choose a category based on user input

**Comment by enasskmal** [comment]
It's true I know. We did not have time to do both. If we had time, we would make the second one. And also add the list of shortcuts to the countries to facilitate the user.
